# Generated by Django 3.2.21 on 2023-09-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='birthdate',
        ),
    ]
